name: storyme_release
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  



  cupertino_icons: ^1.0.6
  firebase_core:
  firebase_auth: ^4.16.0
  cloud_firestore:
  flutterflow_ui: ^0.2.0+1
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  http: ^0.13.6
  provider: ^6.0.4
  flutter_tts: ^3.8.5
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.0.1
  flutter_animate: ^4.1.1+1
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/images/
    - assets/images/books/
    - assets/images/styles/
    - assets/books/3_little_pigstxt/es/

  uses-material-design: true

    
fonts:
  - family: DARKLANDS
    fonts:
      - asset: assets/fonts/Darklands.ttf

 