name: storymev50b2
description: "StoryMe"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutterflow_ui: ^0.2.0+1
  url_launcher: ^6.0.9
  carousel_slider: ^4.2.1
  google_fonts: 4.0.3
  http: ^0.13.6
  provider: ^6.0.4
  flutter_animate: ^4.1.1+1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/books/3_little_pigs/es/book.txt
    - assets/images/
    - assets/fonts/

  fonts:
    - family: DARKLANDS
      fonts:
        - asset: assets/fonts/Darklands.ttf
    - family: Eczar
      fonts:
        - asset: assets/fonts/Eczar-VariableFont_wght.ttf   
    


