#   ____  _                   __  __      
# / ___|| |_ ___  _ __ _   _|  \/  | ___ 
# \___ \| __/ _ \| '__| | | | |\/| |/ _ \
#  ___) | || (_) | |  | |_| | |  | |  __/
# |____/ \__\___/|_|   \__, |_|  |_|\___|
#                      |___/             

# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXXXKKKK00000000000000KKKKKXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXKK0000000000000000000000000000000000KKKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXK00000000000000000KKKKKKKKKK0000000000000000000KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKK00000000000KKKKXXXNNNNNNNNNNNNNNNNNXXXXKKK0000000000000KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKK0KK00000KKKXXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXXKK0000000000KKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKK00KK0KKKKXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWNNXXKK000000000KKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKK0KKK00KKXXXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXNNXKK000000000KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKK00KKXNNW0c;cdk0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXK0Oxl:kNWWNXKK000000000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXK0KK000KKXXNNNWWk:ldooodO0XNWWWWWWWWWWWWWWWWWWWWWWWWWNXK0kxdoloo:xNWWWWNNXK000000000KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0KK000KKXNNNNWWWNklkKkollodxk0XNWWWWNNNNNWWWWWWWWWWNX0OkxdolcldOOlxWWWWWWNNNXK000000000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0KK00K0KXNNNNNWWWWNOdOKOdlclloodxOXNWXOxxkkO00KNWWWNKkxxdolc::ldk00xONWWWWWWWWNNNX000000000KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0000000KXNNNNNWWWWWWN0x0KOdlccccclodx0XKkoll:cood0XNKkddolllc;;cldk00k0WWWWWWWWWNNNNXXK00000000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0K00000KXNWWWWWWWWWWWW0dOKOxolc::::clooddllccllllodxxolllc:::;:cloxO0OxKWWWWWWWWWWWNWNNXK00000000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0000000KXNWWWWWWWWWWWWWWKdd00xolcc:;;:clooooooodddddddoollc:;,;:clodkO0xxXWWWWWWWWWWWWWWNNXKK0000000KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0000000KNNWWWWWWWWWWWWWWWXdlx0kdolc:::ldxxxxxxxxxxxxxxkkkxxdoc:::codkOOxokNWWWWWWWWWWWWWWWWNXKK0000000KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0000000XNNWWWWWWWWWWWWWWWWNkclkOkdollodxxxxkkkkkkkkkkkkkkkkkkkxdolodkOOxldKWWWWWWWWWWWWWWWWWWNXKK0000000KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0000000KNWWNWWWWWWWWWWWWWWWWXd:lxxddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkdco0WWWWWWWWWWWWWWWWWXXNNKKK0O00000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0000000KNNWWNNWWWWWWWWWWWWWWWWKo;cdxxkkxxdddxkkkkkkkkkkkkkkkkxxxxxkkkkxo:l0WWWWWWWWWWWWWWWWWWNNWWXKXK0OO0000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0000000KXNWNXKKXXXNWWWWWWWWWWWWKdodxxxxxdoolccoxxxxxxxxxxxxxdoloooddxkkkxdx0NWWWWWWWWWWWNXKXNWWWWWNKKXKOOOOOO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMN00000000XNWNXK00KKKXWWWWWWWWWWN0xdxxxddddooolcc:lddxxxxxxxxdocclloooddddxxxdx0NWWWWWWWWWNKkxxOKNWWNNK0XX0OOOOOO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMNK0000000KNWWNXXKKXNNNWWWWWWWWNKkddddddoolc:;,'',;;loddddddddoc;,'',;:clloodddddkKWWWWWWWWXOxxkxOXWNKOOOKX0OOOOOOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMWX00000000XWWWWWWWNWWWWWWWWWWWXOdoooooollc:,':l;...,:loooodddoc,...,l;',:cllooooodkKNWWWWWWWNXXXXNWWXOOOk0XKOOOOOOO0NMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMWK0000000KNWWWWNNWWWWWWWWWWWWX0xooooollcc:;,;kk,   .,coooooool;..  'xk:,::cclllloodkKNWWWWWWWWNNWWWWNK00O0XX0OOOOOOOKWMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMN00000000XNWWWNKKNWWWWWWWWWN0kdololllodkkOOkkkx:....;lddddxxdl;....,okkkOkkxdlllllldk0XWWWWWW0x0WWWWWWNNX0XN0OOOOOOO0NMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWX00000000XWWWWWNNWWWWWWWWWWNXOxolloxOKNNNNNNNNXKOdc;:oxxxxxkkdc:cdOKXNNNNNNNX0xollodOXNWWWWNXxoKWWWWWWWWXKXN0OOOOOOOOXMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWKO0OO000KNWWWWWWWWWWNXKXWWWWXkddddOXNNNNXXXKKKK00OkoldxxxxkkkxodO0KKKKKKXXNNNXX0xddxkKWWWNNNXdxNWWWWWWWWX0XN0OOOOOOOOKWMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMN0OOOOOO0KNWWWWWWWWNKOxxkXWWWWNXXXXXXXXXXXXXXKK0OxdxkOxl::::cdOOkkO00KXXXXXXXXXXXXXNNWWWNNNNXKdkNWWWWWWWWX0XN0OOOOOOkOKWMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMN0OOOOOOOKNWWWWWNXXNX0kkk0NWWWWWWWWNNNNXK000OOkkxxdkKN0:   ..cKNKkkOO000000KXNNNWWWWWWNNNNXXK0dkWWWWWWWWWK0XN0OOkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMXOOOOOOOOKNWWWWWWNNWWNNNWWWWWWWWWWWWWWWWNXXK0ocloooox00kc,,cokK0kxxxxoco0XXNWWWWWWWWN00KKXXKK0dOWWWWWWWWN0OXX0kkkkkkkk0WMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMXOOOOOOOOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;;odddddddxxdoxxxkkkkkkkxl;dXWWWWWWWWWNOdxxk0XKK0xONWWWWWWWNOOXXOkkkkkkkk0WMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMXOOOOOOOOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc,okOOkkkkkkkkkkkkOOO00000Ol;kNWWWWWWWW0dodddkKXXKkONWWWWWWWXkOXKkkkkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMN0kOOOOOOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk;cOKK00000OOO000000000KKXKKk:lKWWWWWWWXxlooddxkOO000NWWWWWWN0x0X0kkkkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMN0kkkkkkk0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx:oO0XXXKKK0000KKKKKKKKXXX0kxcl0WWWWWWNkllodddddddxkONWWWWWWXkxKXOxxxkkkkxkXMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMN0kkkkkkk0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOlllx0XXXXXKKKKKXXXXXXXXXKxcclxXWWWWWXxc:lodddddddddOXWWWWWNKxkXKkxxxxxxxxONMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWKOkkkkkkOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOollllok0XNXXXXXXXXXXNNX0xoccllokNWWXOl;;clodddddddddONWWWWNKxx0KOxxxxxxxxk0WMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMNOkkkkdxk0NWNXNWWWWWWWWWWWWWWWWWWWWWWWWXkl:loolccoKNNNNNXXNNNNNNKo;:cloolcdkd:,',:coddddddddddONWWWWNXKKXOxxxxxxxxxkXMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMW0xdxxdoox0NNKXNWWWWWWWWWWWWWWWWWWWWWWKxlc:lodolc:d0XNNNNNNNNNNKd;;:llooc:cc;'',;:cloodddddddxKNWWWWWWWNKxxxxxxxxxx0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMXkodxdxdoxKNXKXWWWWWWWWWWWWWWWWWWWWWNOoolccldoll:;ck00KXXNNKOxc,;:clolc::cll;',;::clodddooookXWWWWWWWNKkxxxxxxxxxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMW0kxxdxxxxOXXKKXNWWWWWWWWWWWWWWWWWWWXkoooc::odolc;,:clk0KK0xc;,,:clol:;:clol;',,;:cllllllllxXNWWNNWWNXOxxxxxxxxxxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxooxxxx0XKOO0KNWWWWWWWWWWWWWWWWWXkoolc:;:oool:;;:clddolc:;,;clll:,;:cll:,'',;;::::::clxXNWNNNWNNXOxxdddddddx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdodxxxxkKX0OkOKNWWWWWWWWWWWWWWWWNOolcc:;,:oooc;;:ccccccc:,;:lll:,,;::c:,'''',,,,,;:ld0XNNNNNNNNXOdddddddddxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMWNXXNWMMMMWKkdxddxxk0NXKKKXNWWWWWWWWWWWWWWWWWXxc::;;,,:odl:;:cccccc:;,;cll:'',,;;:;;;:cloodxkO0XWWWWWWWWWWNKkxxxddddddONMMMMWNNXXNWMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMWKOOOO0NMMMMWKkddk0XNNWWWWWWWWWWWWWWWWWWWWNNNNN0dlc:,''';:;'.';::;;;,..',,,'.',:coxkOKXXNNNNNNNNNWWWWWWWWWWWWNNXXKOxddOXMMMMMNXNNNNWMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMWKKXNNNWMMMMMWKOKNWWWWWWWWNNNNNNNNNNNNNNNNXXXXXXKK0kdc;'....  ';;,,'.    ..':lxOKXXXXNNNNNNNNNNNXXXNNNNNWWWWWWWWWWNXOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNWWWWWWNNNNNNNNNNNNNNNNNNNNNXXXXXXXXKK0ko:.... .',''..  ..':dk0KKXXXXXXNXNNNNNNNNNNNXXXXXXNXNNNNWWWWWWNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXNWWWWWNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNXXXKK0Oxc... ..'....  .'okO0KKXXXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXNWWWWWWNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWNXXNWWWWWWNNNNNNXXXKK0000OOOOOOOO000KKXNNNNNXXK0kc.     ... ..  'dO0KKXNNNWWNNXKK0OOOOOkkkkOOO000KKXXXXNNNNNWWWWWNXNNWMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMWNXXNNNNXXKK00OOkkxxdddddddddddddddddoddddxkkO0KXNX0d,....  ..... .;x0KXNNNX0OkkxdooooooooooooooolooooddxkkO00KKXXNNWWNNXNWMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMWNXXNNXK0OkxxxdddxxxkkkkkOOOOOOOOOOOkkkkkkkkxxddddxk0KX0d:'',;;,'',:oOKXXK0OxdddddxxxkkkkkkOOOOOOOOkkkkkkxxxdddddxkkOKXNNWNNXNWWMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMNK0KK00OkkkkkkkkOOOO0000000000000000000OOOOOOOOkkxxdddxk0KK0kdlclodOKXXK0kxddxxkkkOOO00000000000000KKKKKKK000OOOkkkkkkkO00KKKK0KNMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMW0xxxxkkkOOOOO00000000000000000000000000000000OOOOOkkxxddxO0KKOdxO0KK0OxxxxxkOOOOO00000000000000KKKKKKKKKKKKKK0000000OOOOOkkkxxONMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMNOkkkkkOOOOOO000000000000000000000000000000000000OOOkkkkxxxxO0K00KK0kxxxkkkOOOOO000000000000000000000K000KKKKK000000000000OOOkkONMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMN0kkkkOOOOO000000000000000000000000000000000000000OOOOOOkkkkkkkOKK0OxxkkkkkOOOOOO00000000000000000000000000000000000000000OOOOOOk0NMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMNKOOOOOOOOOO00000000000000OOOkkxxddddoooooodddxxkOOOOOOOOOOOOkkxddddddxkkkOOkOOOOOO0OOkkxxddddddddddddxxkkOOO000000000000000000OOOOKNMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMWN0OOOOOOOOOOkkkxxddooollccc::;;,,,'''''''''''''',,;:cldxkOOOOOxc'......,okOOOOOOkxollc:;,,''''''''''''''',,;;:::ccllooddxxkkOO00000000XNWMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMWN0xooolllcc:::;;,,,''.....................................';:ldkx;         'dkkdlc:;,'...................................''',,;;::cccloooooxKNMMMMMMMMMMMMMM
# MMMMMMMMMMMMW0l,''''''''''.....''...........................................';,...........';;'..............................................'''''''''''''';lOWMMMMMMMMMMMM
# MMMMMMMMMMMMWKkxxxxxxxxxdddoooollllllllcccccc::::;;;;,,,,,,,,,,,,'''''''....';;;;;;;;;;;;;;;;,'.....''''''''''''''',,,,;;;;;;::::::ccclllllloooddxxxxxxxxxdd0WMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNNNNNXXXXXKKKK00000000000000000OOOkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOO0000KKKKKXXXXXXXXNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

name: story_me_v60b
description: "StoryMe"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutterflow_ui: ^0.2.0+1
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  http: ^0.13.6
  provider: ^6.0.4
  flutter_tts: ^3.8.5
  auto_size_text: ^3.0.0


  
  flutter_animate: any
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/books/3_little_pigs/es/book.txt
    - assets/images/
    - assets/images/languages/
    - assets/images/styles/
    - assets/images/books/
    - assets/fonts/
    - assets/books/images/3_little_pigs/anime/
    
  fonts:
    - family: DARKLANDS
      fonts:
        - asset: assets/fonts/Darklands.ttf
     
    