// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIO4aZzU5c4ZXX5XQDdcrnoNVupCdgO4U',
    appId: '1:841448231741:android:8f6f596afec86a08212b54',
    messagingSenderId: '841448231741',
    projectId: 'storyme-dcd11',
    databaseURL: 'https://storyme-dcd11-default-rtdb.firebaseio.com',
    storageBucket: 'storyme-dcd11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5u79J_u2i7uOBUSlQFBOy3WnczxoEPU',
    appId: '1:841448231741:ios:29e259fb96f7b4f5212b54',
    messagingSenderId: '841448231741',
    projectId: 'storyme-dcd11',
    databaseURL: 'https://storyme-dcd11-default-rtdb.firebaseio.com',
    storageBucket: 'storyme-dcd11.appspot.com',
    iosClientId: '841448231741-vsdd9mg60md9ntgt7l3clh6d9if4ntur.apps.googleusercontent.com',
    iosBundleId: 'com.example.storymev50b2',
  );
}
